on:
  schedule:
  - cron: "00 * * * *"

name: hourly_api_pull

jobs:
  hourly_api_pull:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "httr", "jsonlite", "dplyr", "DBI", "RMariaDB"))
          db_user <- "${{secrets.db_user}}"
          db_pswd <- "${{secrets.db_psw}}"
          db_ip <- "${{secrets.db_ip}}"
          source("pull_messari_data_scheduled.R")
        shell: Rscript {0}
      - name: upload_db
        run: |
          dbWriteTable(database_connection, "Messari_R", full_data, append=T)
          dbDisconnect(database_connection)
        shell: Rscript {0}
        if: always()