on: [push]
    
name: update_data

jobs:
  update_data:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck","httr","jsonlite","dplyr","DBI","RMariaDB","devtools"))
        shell: Rscript {0}
      - name: Pull data and update db and pin
        run: Rscript -e 'db_user <- "${{secrets.db_user}}"' -e 'db_ip <- "${{secrets.db_ip}}"' -e 'db_pswd <- "${{secrets.db_pswd}}"' -e 'source("pull_messari_data_scheduled.R")'
